version: '3.8'

services:
  # Next.js Application
  nextjs:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Security Environment Variables (REQUIRED)
      - SESSION_SECRET=4a8f2e9c1b7d6e3f5a8b2c9d1e4f7a0b3c6d9e2f5a8b1c4d7e0f3a6b9c2e5f8a1b4d7e0f3a6b
      - CSRF_SECRET=9d2e5f8a1b4d7e0f3a6b9c2e5f8a1b4d7e0f3a6b9c2e5f8a1b4d7e0f3a6b9c2e5f8a1b4d7e0f
      - ENCRYPTION_KEY=06b259db817f41fbb73ac82a252a3b30
      - HASH_SALT=dae13683bf304cfb90c3c97b649131aa
      # Firebase Configuration
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAvEe6PF9mnwN8Vqf9wqWUkWA58coXKpiA
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=paymentnew-dae57.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=paymentnew-dae57
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=paymentnew-dae57.firebasestorage.app
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=574988813074
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:574988813074:web:5d0d4e8f9a2b3c1d
      # Application Configuration
      - NEXT_PUBLIC_APP_ENV=production
      - NEXT_PUBLIC_APP_VERSION=1.0.0
      - NEXT_PUBLIC_DOMAIN=scjsnext.com
      # Security Configuration
      - SECURITY_HEADERS_ENABLED=true
      - RATE_LIMIT_MAX_REQUESTS=100
      - RATE_LIMIT_WINDOW_MS=900000
      # Debug Configuration (Production)
      - NEXT_PUBLIC_DEBUG_ENABLED=false
      - NEXT_PUBLIC_LOG_LEVEL=error
    networks:
      - app-network
    volumes:
      - ../Frontend/.env.local:/app/.env.local:ro
      - ../Frontend/.env.production:/app/.env.production:ro

  # Nginx Reverse Proxy (No SSL)
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-no-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - nextjs

networks:
  app-network:
    driver: bridge 