# ====================================================================
# Docker Compose Configuration for Production
# Next.js Payment System v2.0 with Cloudflare SSL Integration
# Optimized for Performance, Security & Reliability
# ====================================================================

services:
  # Next.js Application Container
  nextjs-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
      target: production
      args:
        NODE_ENV: production
    container_name: nextjs-payment-app
    restart: unless-stopped
    
    # Environment Variables
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      
      # Security Secrets
      - SESSION_SECRET=4a8f2e9c1b7d6e3f5a8b2c9d1e4f7a0b3c6d9e2f5a8b1c4d7e0f3a6b9c2e5f8a1b4d7e0f3a6b
      - CSRF_SECRET=9d2e5f8a1b4d7e0f3a6b9c2e5f8a1b4d7e0f3a6b9c2e5f8a1b4d7e0f3a6b9c2e5f8a1b4d7e0f
      - ENCRYPTION_KEY=06b259db817f41fbb73ac82a252a3b30
      - HASH_SALT=dae13683bf304cfb90c3c97b649131aa
      
      # Firebase Configuration
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAvEe6PF9mnwN8Vqf9wqWUkWA58coXKpiA
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=paymentnew-dae57.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=paymentnew-dae57
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=paymentnew-dae57.firebasestorage.app
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=1074850368558
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:1074850368558:web:f7c3c3f162dfc8af1fa3bf
      
      # Application Settings
      - NEXT_PUBLIC_APP_ENV=production
      - NEXT_PUBLIC_APP_VERSION=2.0.0
      - NEXT_PUBLIC_DOMAIN=scjsnext.com
      
      # Security Configuration
      - SECURITY_HEADERS_ENABLED=true
      - RATE_LIMIT_MAX_REQUESTS=100
      - RATE_LIMIT_WINDOW_MS=900000
      - FORCE_HTTPS=false
      - SECURE_COOKIES=true
      - CLOUDFLARE_SSL=true
      
      # Performance Settings
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_DEBUG_ENABLED=false
      - NEXT_PUBLIC_LOG_LEVEL=error
      - NEXT_PUBLIC_SHOW_ERROR_DETAILS=false
    
    # Volume Mounts
    volumes:
      - app-data:/app/data
      - app-logs:/app/logs
    
    # Port Mapping (for health checks from host)
    ports:
      - "3000:3000"
    
    # Network Configuration
    networks:
      - payment-network
    
    # Health Check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--timeout=10", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    
    # Security Settings
    user: "1001:1001"
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
      - /app/.next/cache
    
    security_opt:
      - no-new-privileges:true
    
    cap_drop:
      - ALL
    
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    
    # Resource Limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.8'
        reservations:
          memory: 512M
          cpus: '0.4'

  # Nginx Reverse Proxy for Cloudflare
  nginx-proxy:
    image: nginx:1.25-alpine
    container_name: nginx-cloudflare-proxy
    restart: unless-stopped
    
    # Port Mapping (Only HTTP - Cloudflare handles HTTPS)
    ports:
      - "80:80"
    
    # Volume Mounts
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx-logs:/var/log/nginx
      - nginx-cache:/var/cache/nginx
      - nginx-temp:/var/cache/nginx/temp
    
    # Network Configuration
    networks:
      - payment-network
    
    # Dependencies
    depends_on:
      nextjs-app:
        condition: service_healthy
    
    # Health Check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--timeout=5", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Security Settings
    security_opt:
      - no-new-privileges:true
    
    # Resource Limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

# Network Configuration
networks:
  payment-network:
    driver: bridge
    name: payment-system-network
    driver_opts:
      com.docker.network.bridge.name: payment-br0

# Volume Configuration
volumes:
  # Application Data
  app-data:
    driver: local
    name: payment-app-data
  
  # Application Logs
  app-logs:
    driver: local
    name: payment-app-logs
  
    
  # Nginx Logs
  nginx-logs:
    driver: local
    name: payment-nginx-logs
  
  # Nginx Cache
  nginx-cache:
    driver: local
    name: payment-nginx-cache
    
  # Nginx Temp
  nginx-temp:
    driver: local
    name: payment-nginx-temp